In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

import warnings 
warnings.filterwarnings("ignore")

In [2]:
iris = pd.read_csv('IRIS Flower Classification.csv')
iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
#FEATURES & TARGET

X=iris.drop("species",axis=1)
Y=iris["species"]

In [6]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [7]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [8]:
#train_test_split

X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.3,random_state=1)

In [9]:
X_train.shape

(105, 4)

In [10]:
X_test.shape

(45, 4)

In [11]:
for col in X:
    ss=StandardScaler()
    X_train[col]=ss.fit_transform(X_train[[col]])
    X_test[col]=ss.transform(X_test[[col]])

In [12]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
118      2.260502    -1.048543      1.776917     1.422614
18      -0.118974     1.855115     -1.146243    -1.139555
4       -0.951790     1.371172     -1.314886    -1.267663
45      -1.189738    -0.080657     -1.314886    -1.139555
59      -0.713843    -0.806572      0.090479     0.269638
..            ...          ...           ...          ...
133      0.594869    -0.564600      0.765054     0.397746
137      0.713843     0.161314      0.989912     0.782071
72       0.594869    -1.290514      0.652625     0.397746
140      1.070764     0.161314      1.046127     1.550722
37      -1.070764     0.161314     -1.258672    -1.395772

[105 rows x 4 columns]

In [13]:
X_test

     sepal_length  sepal_width  petal_length  petal_width
14       0.000000     2.339057     -1.427316    -1.267663
98      -0.832816    -1.290514     -0.415453    -0.114688
75       0.951790    -0.080657      0.371552     0.269638
16      -0.475895     2.097086     -1.371101    -1.011447
131      2.498449     1.855115      1.495844     1.038288
56       0.594869     0.645257      0.540196     0.525855
141      1.308712     0.161314      0.765054     1.422614
44      -0.832816     1.855115     -1.033813    -1.011447
29      -1.308712     0.403286     -1.202457    -1.267663
120      1.308712     0.403286      1.102342     1.422614
94      -0.237948    -0.806572      0.259123     0.141529
5       -0.475895     2.097086     -1.146243    -1.011447
102      1.546659    -0.080657      1.214771     1.166397
51       0.713843     0.403286      0.427766     0.397746
78       0.237948    -0.322629      0.427766     0.397746
42      -1.665633     0.403286     -1.371101    -1.267663
92       0.000000    -1.048543      0.146693     0.013421
66      -0.237948    -0.080657      0.427766     0.397746
31      -0.475895     0.887229     -1.258672    -1.011447
35      -0.951790     0.403286     -1.427316    -1.267663
90      -0.356921    -1.048543      0.371552     0.013421
84      -0.475895    -0.080657      0.427766     0.397746
77       1.070764    -0.080657      0.708839     0.653963
40      -0.951790     1.129200     -1.371101    -1.139555
125      1.665633     0.403286      1.270985     0.782071
99      -0.118974    -0.564600      0.202908     0.141529
33      -0.356921     2.823000     -1.314886    -1.267663
19      -0.832816     1.855115     -1.258672    -1.139555
73       0.356921    -0.564600      0.540196     0.013421
146      0.594869    -1.290514      0.708839     0.910180
91       0.356921    -0.080657      0.483981     0.269638
135      2.260502    -0.080657      1.327200     1.422614
69      -0.237948    -1.290514      0.090479    -0.114688
128      0.713843    -0.564600      1.046127     1.166397
114      0.000000    -0.564600      0.765054     1.550722
48      -0.594869     1.613143     -1.258672    -1.267663
53      -0.356921    -1.774457      0.146693     0.141529
28      -0.713843     0.887229     -1.314886    -1.267663
54       0.832816    -0.564600      0.483981     0.397746
108      1.070764    -1.290514      1.158556     0.782071
112      1.189738    -0.080657      0.989912     1.166397
17      -0.832816     1.129200     -1.314886    -1.139555
119      0.237948    -2.016429      0.708839     0.397746
103      0.594869    -0.322629      1.046127     0.782071
58       0.951790    -0.322629      0.483981     0.141529

In [14]:
knn=KNeighborsClassifier(n_neighbors=5)#DEFAULT KNN=5

In [15]:
knn.fit(X_train,Y_train)

KNeighborsClassifier()

KNeighborsClassifier()
In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [16]:
y_pred=knn.predict(X_test)

In [17]:
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor'], dtype=object)

In [18]:
from sklearn.metrics import classification_report

In [19]:
print(classification_report(Y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      0.94      0.94        18
 Iris-virginica       0.92      0.92      0.92        13

       accuracy                           0.96        45
      macro avg       0.96      0.96      0.96        45
   weighted avg       0.96      0.96      0.96        45